libxt_TOS: fix compilation error
Fix compilation error caused by double definition of IPPROTO_SCTP:

In file included from /usr/include/netinet/ip.h:25,
                 from /usr/include/linux/ip.h:19,
                 from tos_values.c:4,
                 from libxt_TOS.c:15:
/usr/include/netinet/in.h:84: error: expected identifier before numeric constant
make[2]: *** [libxt_TOS.oo] Error 1

Signed-off-by: Patrick McHardy <kaber@trash.net>